connector.name=hive

hive.metastore.uri=thrift://hive-metastore:9083

hive.config.resources=/opt/hadoop-config/core-site.xml,/opt/hadoop-config/hdfs-site.xml

hive.metastore-cache-ttl=30s

hive.metastore-refresh-interval=30s

hive.file-status-cache-tables=*

hive.file-status-cache-expire-time=30s

hive.partition-statistics-sample-size=1000

# Para tablas externas
hive.non-managed-table-writes-enabled=true