connector.name=hive

fhive.metastore.uri=thrift://hive-metastore:9083

hive.config.resources=/opt/hadoop-config/core-site.xml,/opt/hadoop-config/hdfs-site.xml

# Metadata Caching (Basic)
hive.metastore-cache-ttl=10m
hive.metastore-refresh-interval=5m

# Optimization for Parquet
hive.parquet.use-column-names=true

# Para tablas externas
hive.non-managed-table-writes-enabled=true

# Performance tweaks (Standard)
hive.max-partitions-per-scan=100000
