version: '3.8'

volumes:
  envoy-logs:

networks:
  simple-producer_logging-net:
    external: true

services:
  app:
    build: .
    container_name: simple-server-app
    networks:
      - simple-producer_logging-net

  envoy:
    image: envoyproxy/envoy:v1.35.3
    container_name: envoy-sidecar
    networks:
      - simple-producer_logging-net
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - envoy-logs:/var/log/envoy:z 
    user: "0:0"
    ports:
      - "8081:8080"
      - "9902:9901"
    depends_on:
      - app
    environment:
      - ENVOY_UID=0
      - ENVOY_GID=0
      - SERVICE_NAME=products-api-v1
      - INSTANCE_ID=123

  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit-sidecar
    networks:
      - simple-producer_logging-net
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      # Mount the shared volume as read-only
      - envoy-logs:/var/log/envoy:ro
    depends_on:
      - envoy