version: '3.8'

networks:
  logging-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper
    networks:
      - logging-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.6'
    container_name: kafka
    networks:
      - logging-net
    ports:
      - '9092:9092'
    environment:
      # Use the service name 'kafka' for the advertised listener, as it will be resolved on the shared network.
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-consumer:
    image: bitnami/kafka:3.6
    container_name: kafka-consumer
    networks:
      - logging-net
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c", "sleep 15 && kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic envoy-logs --from-beginning" ]
