events { worker_connections 1024; }
http {
    server {
        listen 80;
        location /app1 {
            proxy_pass http://zone2-app1-envoy:8080;
            proxy_http_version 1.1;
        }
        location /app2 {
            proxy_pass http://zone2-app2-envoy:8080;
            proxy_http_version 1.1;
        }
    }
}
