apiVersion: 1

datasources:
  - name: Trino-HDFS
    type: trino-datasource
    uid: trino-hdfs-uid
    url: http://trino:8080
    access: proxy
    jsonData:
      user: admin
      catalog: hive
      schema: default
    editable: true

  - name: Redis-Global
    type: redis-datasource
    uid: redis-uid
    url: global-redis:6379

    access: proxy
    editable: true
